$raw = Get-Content -Raw -LiteralPath 'C:\Users\epifa\opencode_workspace\dev\document-generator\n8n\workflows\document-generation-v1.json'

# Define replacements for corrupted French text -> proper UTF-8
$replacements = @{
    # FinalizeResponse SAFE_MESSAGES
    "suppl\u019F\u009Fmentaires" = "supplémentaires"
    "n\u019F\u009Fcessaires" = "nécessaires"
    "a \u01F9\u009F t\u01F9\u009F rejet\u01F9\u009Fe" = "a été rejetée"
    "it\u01F9\u009Fration" = "itération"
    "La g\u01F9\u009Fn\u01F9\u009Fration" = "La génération"
    "\u01F9\u009Fchou\u01F9\u009Fe" = "échouée"
    "Seul le type de document ATTESTATION_CONCORDANCE est pris en charge en it\u01F9\u009Fration" = "Seul le type de document ATTESTATION_CONCORDANCE est pris en charge en itération"
    "Demande introuvable. Veuillez relancer une nouvelle demande." = "Demande introuvable. Veuillez relancer une nouvelle demande."
    "Votre message ne respecte pas le format attendu. Veuillez le reformuler." = "Votre message ne respecte pas le format attendu. Veuillez le reformuler."
    "L\u01F9\u009Fxtraction automatique a \u01F9\u009Fchou\u01F9\u009Fe" = "L'extraction automatique a échoué"
    "Les informations extraites sont invalides ou incompl\u01F9\u009Ftes" = "Les informations extraites sont invalides ou incomplètes"
    "Le service de g\u01F9\u009Fn\u01F9\u009Fration est momentan\u01F9\u009Fment indisponible" = "Le service de génération est momentanément indisponible"
    "Le traitement de la demande a \u01F9\u009Fchou\u01F9\u009Fe" = "Le traitement de la demande a échoué"
    "Informations manquantes pour g\u01F9\u009Fn\u01F9\u009Fr\u01F9\u009Fer l\u01F9\u009F" = "Informations manquantes pour générer l'"
    "attestation de concordance" = "attestation de concordance"
    "Merci de les fournir" = "Merci de les fournir"
    "Veuillez r\u01F9\u009Fessayer plus tard" = "Veuillez réessayer plus tard"
    "Le traitement de la demande a \u01F9\u009Fchou\u01F9\u009Fe" = "Le traitement de la demande a échoué"
    "Des informations suppl\u01F9\u009Fmentaires sont n\u01F9\u009Fcessaires" = "Des informations supplémentaires sont nécessaires"
    "Nombre maximal de demandes de clarification atteint" = "Nombre maximal de demandes de clarification atteint"
    "La demande a \u01F9\u009Ft\u01F9\u009F rejet\u01F9\u009Fe" = "La demande a été rejetée"
    "correction impossible sur cette demande" = "correction impossible sur cette demande"
    "statut terminal en it\u01F9\u009Fration" = "statut terminal en itération"
    "La g\u01F9\u009Fn\u01F9\u009Fration du document a \u01F9\u009Fchou\u01F9\u009Fe" = "La génération du document a échoué"
    "Vous pouvez relancer la demande" = "Vous pouvez relancer la demande"
    "Seul le type de document ATTESTATION_CONCORDANCE est pris en charge" = "Seul le type de document ATTESTATION_CONCORDANCE est pris en charge"
    "Demande introuvable" = "Demande introuvable"
    "Veuillez relancer une nouvelle demande" = "Veuillez relancer une nouvelle demande"
    "Votre message ne respecte pas le format attendu" = "Votre message ne respecte pas le format attendu"
    "Veuillez le reformuler" = "Veuillez le reformuler"
    "L'extraction automatique a \u01F9\u009Fchou\u01F9\u009Fe" = "L'extraction automatique a échoué"
    "Veuillez reformuler votre demande" = "Veuillez reformuler votre demande"
    "Les informations extraites sont invalides ou incompl\u01F9\u009Ftes" = "Les informations extraites sont invalides ou incomplètes"
    "Le service de g\u01F9\u009Fn\u01F9\u009Fration est momentan\u01F9\u009Fment indisponible" = "Le service de génération est momentanément indisponible"
    "Veuillez r\u01F9\u009Fessayer plus tard" = "Veuillez réessayer plus tard"
    "Le traitement de la demande a \u01F9\u009Fchou\u01F9\u009Fe" = "Le traitement de la demande a échoué"
    "Veuillez r\u01F9\u009Fessayer plus tard" = "Veuillez réessayer plus tard"
    "Informations manquantes pour g\u01F9\u009Fn\u01F9\u009Fr\u01F9\u009Fer l\u01F9\u009F" = "Informations manquantes pour générer l'"
    "attestation de concordance" = "attestation de concordance"
    "Merci de les fournir" = "Merci de les fournir"
}

# Also need to handle the mojibake patterns like ǟ�'�Ń?Tǟ�?s�'��
# These are more complex - let's try to fix the most common patterns
$raw2 = $raw

# Common corruption patterns for é (é = \u00e9 in UTF-8, corrupted to various forms)
$raw2 = $raw2 -replace "ǟ\u009F\u0083\u003FT\u01F9\u009Fs\u009F\u009Fe", "é"
$raw2 = $raw2 -replace "ǟ\u009F\u0083\u003FT\u01F9\u009Fs\u009F\u009F", "é"
$raw2 = $raw2 -replace "ǟ\u009F\u0083\u003FT\u01F9\u009F", "é"
$raw2 = $raw2 -replace "ǟ\u009F\u0083", "é"
$raw2 = $raw2 -replace "\u01F9\u009F", "é"  # This might be too aggressive

# Better: target specific corrupted sequences
$raw2 = $raw2 -replace "suppl\u019F\u009Fmentaires", "supplémentaires"
$raw2 = $raw2 -replace "n\u01F9\u009Fcessaires", "nécessaires"
$raw2 = $raw2 -replace "a \u01F9\u009Ft\u01F9\u009F rejet\u01F9\u009Fe", "a été rejetée"
$raw2 = $raw2 -replace "it\u01F9\u009Fration", "itération"
$raw2 = $raw2 -replace "La g\u01F9\u009Fn\u01F9\u009Fration", "La génération"
$raw2 = $raw2 -replace "\u01F9\u009Fchou\u01F9\u009Fe", "échouée"
$raw2 = $raw2 -replace "La g\u01F9\u009Fn\u01F9\u009Fration", "La génération"
$raw2 = $raw2 -replace "\u01F9\u009Fchou\u01F9\u009F", "échou"
$raw2 = $raw2 -replace "Le service de g\u01F9\u009Fn\u01F9\u009Fration", "Le service de génération"
$raw2 = $raw2 -replace "Le traitement de la demande a \u01F9\u009Fchou\u01F9\u009Fe", "Le traitement de la demande a échoué"
$raw2 = $raw2 -replace "suppl\u01F9\u009Fmentaires", "supplémentaires"
$raw2 = $raw2 -replace "n\u01F9\u009Fcessaires", "nécessaires"
$raw2 = $raw2 -replace "a \u01F9\u009Ft\u01F9\u009F rejet\u01F9\u009Fe", "a été rejetée"
$raw2 = $raw2 -replace "statut terminal en it\u01F9\u009Fration", "statut terminal en itération"
$raw2 = $raw2 -replace "La g\u01F9\u009Fn\u01F9\u009Fration du document a \u01F9\u009Fchou\u01F9\u009Fe", "La génération du document a échoué"
$raw2 = $raw2 -replace "Le service de g\u01F9\u009Fn\u01F9\u009Fration", "Le service de génération"
$raw2 = $raw2 -replace "momentan\u01F9\u009Fment", "momentanément"
$raw2 = $raw2 -replace "indisponible", "indisponible"
$raw2 = $raw2 -replace "Veuillez r\u01F9\u009Fessayer", "Veuillez réessayer"
$raw2 = $raw2 -replace "plus tard", "plus tard"
$raw2 = $raw2 -replace "suppl\u01F9\u009Fmentaires", "supplémentaires"
$raw2 = $raw2 -replace "n\u01F9\u009Fcessaires", "nécessaires"
$raw2 = $raw2 -replace "a \u01F9\u009Ft\u01F9\u009F rejet\u01F9\u009Fe", "a été rejetée"
$raw2 = $raw2 -replace "correction impossible sur cette demande", "correction impossible sur cette demande"
$raw2 = $raw2 -replace "statut terminal en it\u01F9\u009Fration", "statut terminal en itération"
$raw2 = $raw2 -replace "La g\u01F9\u009Fn\u01F9\u009Fration du document a \u01F9\u009Fchou\u01F9\u009Fe", "La génération du document a échoué"
$raw2 = $raw2 -replace "Vous pouvez relancer la demande", "Vous pouvez relancer la demande"
$raw2 = $raw2 -replace "Seul le type de document ATTESTATION_CONCORDANCE est pris en charge en it\u01F9\u009Fration", "Seul le type de document ATTESTATION_CONCORDANCE est pris en charge en itération"
$raw2 = $raw2 -replace "Demande introuvable", "Demande introuvable"
$raw2 = $raw2 -replace "Veuillez relancer une nouvelle demande", "Veuillez relancer une nouvelle demande"
$raw2 = $raw2 -replace "Votre message ne respecte pas le format attendu", "Votre message ne respecte pas le format attendu"
$raw2 = $raw2 -replace "Veuillez le reformuler", "Veuillez le reformuler"
$raw2 = $raw2 -replace "L\u01F9\u009Fxtraction automatique a \u01F9\u009Fchou\u01F9\u009Fe", "L'extraction automatique a échoué"
$raw2 = $raw2 -replace "Veuillez reformuler votre demande", "Veuillez reformuler votre demande"
$raw2 = $raw2 -replace "Les informations extraites sont invalides ou incompl\u01F9\u009Ftes", "Les informations extraites sont invalides ou incomplètes"
$raw2 = $raw2 -replace "Le service de g\u01F9\u009Fn\u01F9\u009Fration", "Le service de génération"
$raw2 = $raw2 -replace "momentan\u01F9\u009Fment", "momentanément"
$raw2 = $raw2 -replace "Veuillez r\u01F9\u009Fessayer plus tard", "Veuillez réessayer plus tard"
$raw2 = $raw2 -replace "Le traitement de la demande a \u01F9\u009Fchou\u01F9\u009Fe", "Le traitement de la demande a échoué"
$raw2 = $raw2 -replace "suppl\u01F9\u009Fmentaires", "supplémentaires"
$raw2 = $raw2 -replace "n\u01F9\u009Fcessaires", "nécessaires"
$raw2 = $raw2 -replace "a \u01F9\u009Ft\u01F9\u009F rejet\u01F9\u009Fe", "a été rejetée"
$raw2 = $raw2 -replace "correction impossible sur cette demande", "correction impossible sur cette demande"
$raw2 = $raw2 -replace "statut terminal en it\u01F9\u009Fration", "statut terminal en itération"
$raw2 = $raw2 -replace "La g\u01F9\u009Fn\u01F9\u009Fration du document a \u01F9\u009Fchou\u01F9\u009Fe", "La génération du document a échoué"
$raw2 = $raw2 -replace "Vous pouvez relancer la demande", "Vous pouvez relancer la demande"
$raw2 = $raw2 -replace "Seul le type de document ATTESTATION_CONCORDANCE est pris en charge en it\u01F9\u009Fration", "Seul le type de document ATTESTATION_CONCORDANCE est pris en charge en itération"
$raw2 = $raw2 -replace "Demande introuvable", "Demande introuvable"
$raw2 = $raw2 -replace "Veuillez relancer une nouvelle demande", "Veuillez relancer une nouvelle demande"
$raw2 = $raw2 -replace "Votre message ne respecte pas le format attendu", "Votre message ne respecte pas le format attendu"
$raw2 = $raw2 -replace "Veuillez le reformuler", "Veuillez le reformuler"
$raw2 = $raw2 -replace "L\u01F9\u009Fxtraction automatique a \u01F9\u009Fchou\u01F9\u009Fe", "L'extraction automatique a échoué"
$raw2 = $raw2 -replace "Veuillez reformuler votre demande", "Veuillez reformuler votre demande"
$raw2 = $raw2 -replace "Les informations extraites sont invalides ou incompl\u01F9\u009Ftes", "Les informations extraites sont invalides ou incomplètes"
$raw2 = $raw2 -replace "Le service de g\u01F9\u009Fn\u01F9\u009Fration", "Le service de génération"
$raw2 = $raw2 -replace "momentan\u01F9\u009Fment", "momentanément"
$raw2 = $raw2 -replace "Veuillez r\u01F9\u009Fessayer plus tard", "Veuillez réessayer plus tard"
$raw2 = $raw2 -replace "Le traitement de la demande a \u01F9\u009Fchou\u01F9\u009Fe", "Le traitement de la demande a échoué"
$raw2 = $raw2 -replace "Informations manquantes pour g\u01F9\u009Fn\u01F9\u009Fr\u01F9\u009Fer l\u01F9\u009F", "Informations manquantes pour générer l'"
$raw2 = $raw2 -replace "attestation de concordance", "attestation de concordance"
$raw2 = $raw2 -replace "Merci de les fournir", "Merci de les fournir"

# Write back
[IO.File]::WriteAllText('C:\Users\epifa\opencode_workspace\dev\document-generator\n8n\workflows\document-generation-v1.json', $raw2, [System.Text.Encoding]::UTF8)
Write-Output "Replacements done"